name: Generate-AI-docs
description: Generate AI doc
inputs:
  OPENAI_API_KEY:
    description: OPENAI_API_KEY
    required: true
  KNOWL_API_KEY:
    description: KNOWL_API_KEY
    required: true
runs:
  runs-on: ubuntu-latest
  container: public.ecr.aws/t7d0n7r6/knowl-code-to-doc-manual:latest
  steps:
    - name: Setup Environment (Push)  
      run: |  
        echo "COMMIT_SHA=${{ github.sha }}" >> ${GITHUB_ENV}
        echo "REPO_NAME=${{ github.event.repository.name }}" >> ${GITHUB_ENV}
        echo "OWNER_NAME=${{ github.repository_owner }}" >> ${GITHUB_ENV}
        echo "KNOWL_BACKEND_HTTP=https://staging-api.knowl.io/" >> ${GITHUB_ENV}
        echo "BRANCH_NAME=${{ github.ref_name }}" >> ${GITHUB_ENV}
        echo "${{ github.action_path }}" >> "$GITHUB_PATH"
      shell: bash
    - name: Prepare script file
      run: |
          chmod +x "${{ github.action_path }}/run-gen-docs.sh"
          chmod +x "${{ github.action_path }}/bucket_files.sh"
      shell: bash
    - name: ls
      run: ls
      shell: bash
    - name: pwd
      run: pwd
      shell: bash
    - name: Run the script file
      run: run-gen-docs.sh ${{ github.workspace }}
      shell: bash
      env:
        OPENAI_API_KEY: ${{inputs.OPENAI_API_KEY}}
        KNOWL_API_KEY: ${{inputs.KNOWL_API_KEY}}
