name: Generate-AI-docs
description: Generate AI doc
inputs:
  OPENAI_API_KEY:
    description: OPENAI_API_KEY
    required: true
  KNOWL_API_KEY:
    description: KNOWL_API_KEY
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'